### ISSUE TITLE
Getting a compile error

### ISSUE THREAD

**Issue by nhlives** [fabianoriccardi/esp-logger#1]
Seems I'm getting a multiple libraries error. It has been working on this system but suddenttly I'm seeing this error.  Reinstalled and downleved to IDE 1.8 from 1.9.  Same error.

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp: In function 'bool copyFile(String, String)':

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:121:44: error: 'O_TRUNC' was not declared in this scope

   File d=SD.open(destination, FILE_WRITE | O_TRUNC);

                                            ^

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:121:44: note: suggested alternative:

In file included from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatFile.h:36:0,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/ArduinoFiles.h:33,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatLib.h:27,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/SdFat.h:33,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SDFS\src/SDFS.h:36,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SD\src/SD.h:25,

                 from D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:30:

C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatApiConstants.h:81:15: note:   'sdfat::O_TRUNC'

 const uint8_t O_TRUNC = 0X10;

               ^

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp: In member function 'virtual bool LoggerSD::flush()':

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:229:56: error: 'O_TRUNC' was not declared in this scope

         File tempFile=SD.open(tempFilePath, FILE_WRITE|O_TRUNC);

                                                        ^

D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:229:56: note: suggested alternative:

In file included from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatFile.h:36:0,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/ArduinoFiles.h:33,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatLib.h:27,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/SdFat.h:33,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SDFS\src/SDFS.h:36,

                 from C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SD\src/SD.h:25,

                 from D:\Users\jrhol\Documents\Arduino\libraries\ESP_Logger\src\logger_sd.cpp:30:

C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266SdFat\src/FatLib/FatApiConstants.h:81:15: note:   'sdfat::O_TRUNC'

 const uint8_t O_TRUNC = 0X10;

               ^

Multiple libraries were found for "SD.h"
 Used: C:\Users\jrhol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by fabianoriccardi** [comment]
Hi John,
thank you for the feedback. Unfortunately, ESP8266 developers have removed O_TRUNC constant. I have added back it. Now it should work. 
I've released a new version, but Arduino IDE needs a few hours or days to update the library version. If you are hurried, you can clone and install this repo.
Let me know!

**Comment by nhlives** [comment]
I appreciate the rapid response.  You might find it interesting to know your library is being used for a good cause. Check out http://limitedmobility.solutions.


Regards,
John
________________________________

**Comment by nhlives** [comment]
This error is gone: O_TRUNC

But now I seems to be getting file open errors:
[ESP LOGGER] Opening log file error!
[ESP LOGGER] getActualSize() open log file error!
[ESP LOGGER] getActualSize() open log file error!

--> We had 0 attempts before reaching a time server
[ESP LOGGER] Opening log file error!
[ESP LOGGER] getActualSize() open log file error!

I erased flash with the IDE but no help.  I'll close this issue and open a new one.

**Comment by fabianoriccardi** [comment]
I'm glad that this library will be part of such a project!
