### ISSUE TITLE
Apple chip M1 compatibility 

### ISSUE THREAD

**Issue by Mir1001** [fabianoriccardi/esp-logger#15]
After build operation on PlatformIO I get the following error (same as other libs, but if I update them error was gone):
> Error: Could not find the package with 'fabiuz7/ESP Logger @ ^2.0.0' requirements for your system 'darwin_arm64'

**Comment by fabianoriccardi** [comment]
try with `fabianoriccardi/ESPLogger@^2.0.0`

**Comment by Mir1001** [comment]
It works. Thanks.
