### ISSUE TITLE
[ESP LOGGER] Opening log file error!

### ISSUE THREAD

**Issue by nhlives** [fabianoriccardi/esp-logger#2]
With the latest build, I am getting:
[ESP LOGGER] Opening log file error!
[ESP LOGGER] getActualSize() open log file error!
[ESP LOGGER] getActualSize() open log file error!

--> We had 0 attempts before reaching a time server
[ESP LOGGER] Opening log file error!
[ESP LOGGER] getActualSize() open log file error!

**Comment by fabianoriccardi** [comment]
Hi,
have you tried with previous SDK (ie. v2.5.0)? May you describe your configuration (SPIFFS or SD)?

**Comment by nhlives** [comment]
Somehow my option for Flash Size got changed to 4M(No SPIFFS).  Don't know if that is the now the default for a new install or what.  This has caused me some serious headache. :-(

**Comment by fabianoriccardi** [comment]
This is an annoying but known problem, SPIFFS partitioning info is reset to default every time you change board
