### ISSUE TITLE
Mounting SPIFFS failed

### ISSUE THREAD

**Issue by denxhun** [fabianoriccardi/esp-logger#4]
Hi,
This library looks awesome but I'm unable to use it. Maybe I'm doing something wrong. 
This is what I see when I ran your simple example:
```
Basic log example
Initializing SD card... E (19) SPIFFS: mount failed, -10025
[E][SPIFFS.cpp:72] begin(): Mounting SPIFFS failed! Error: -1
Failed!
```
I'm using latest PlatformIO with Atom, on Windows, the board is a ESPWROOM32.
[build.log](https://github.com/fabiuz7/esp-logger-lib/files/3897653/build.log)

**Comment by fabianoriccardi** [comment]
Hi, 
which version of esp32 arduino core are you using?

**Comment by denxhun** [comment]
Thanks for your instant reply. I'm using a cheap module from China, this is engraved to the moduel: ESP-WROOM-32. There is an FCC id and another nuber on it: 211-1E1007. SW details are in the attached build.log file. I hope this helps.

**Comment by fabianoriccardi** [comment]
Ok, thanks, I didn't see the log! I will check such configuration as soon as possible!

**Comment by denxhun** [comment]
Maybe I got the issue:
https://github.com/espressif/arduino-esp32/issues/638#issuecomment-330022993

If the file path starts with `/spiffs/` then your example works on my machine too.

**Comment by fabianoriccardi** [comment]
Thanks for the hint, I will try to look as soon as possible!

**Comment by fabianoriccardi** [comment]
Hi,
I've tried the first example on Lolin D32 and Lolin D32 PRO, compiling with arduino-esp32 core v1.0.4 (the latest version) in Arduino IDE. In both cases it works...
